@include('home.includes.header')

@yield('section-1')
@yield('section-2')
@yield('section-3')
@yield('section-4')
@yield('section-5')
@yield('section-6')
@yield('section-7')
@yield('section-8')
@yield('section-9')
@yield('section-10')
@yield('section-11')
@yield('section-12')
@yield('section-13')
@yield('section-14')

@include('home.includes.footer')